
--+Migrate Down

DROP TABLE IF EXISTS "robot";

DROP TABLE IF EXISTS "http_endpoint";
DROP TABLE IF EXISTS "endpoint";

DROP TABLE IF EXISTS "task";

--+Migrate Up

CREATE TABLE "task" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "version" BIGINT NOT NULL,
    "context" CHARACTER VARYING(255) NOT NULL,
    "function" CHARACTER VARYING(255) NOT NULL,
    "step" CHARACTER VARYING(255) NOT NULL,
    "status" CHARACTER VARYING(255) NOT NULL,
    "retry" BIGINT NOT NULL DEFAULT 8,
    "arguments" JSONB NOT NULL DEFAULT '{}',
    "buffer" JSONB NOT NULL DEFAULT '{}',
    "creation_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "last_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "endpoint" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "type" CHARACTER VARYING(255) NOT NULL,
    "name" CHARACTER VARYING(255) NOT NULL,
    "creation_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "last_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "endpoint_unique_name" UNIQUE("name")
);

CREATE TABLE "http_endpoint" (
    "method" CHARACTER VARYING(255) NOT NULL,
    "url" CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT "endpoint_http_check" CHECK ("type"='HTTP')
) INHERITS ("endpoint");

CREATE TABLE "robot" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "function" CHARACTER VARYING(255) NOT NULL,
    "version" BIGINT NOT NULL,
    "status" CHARACTER VARYING(255) NOT NULL,
    "definition" JSONB NOT NULL DEFAULT '{}',
    "creation_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "last_update" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

